### ISSUE TITLE
Deduplicate TLDs

### ISSUE THREAD

**Issue by enenumxela** [hueristiq/hqgourl#18]
TLDs at `https://github.com/hueristiq/hqgourl/blob/main/tlds/tlds.go` contain duplicate entries. However, the file is generated by `https://github.com/hueristiq/hqgourl/blob/main/generate/tlds/main.go`. Adjust the generating code to remove duplicate TLDs before writing to file.

**Comment by W1nterFr3ak** [comment]
Added remDuplicates func in https://github.com/hueristiq/hqgourl/blob/main/generate/tlds/main.go initiated pull in dev check
